### ISSUE TITLE
File selection and open routine issue in 3.1.1. (MacOS)

### ISSUE THREAD

**Issue by kayrie** [AdamSmasherDerby/Statsbook-Tool#21]
The file input box appears not to be working properly:

- Choose a file opens the OS file open dialog, after selection of a file nothing else happens
- drag and droping a file in this area is not functioning
- clicking on the new button "Enter Google Sheets URL" is not functioning

May it be, that the new button in the UI is on top of other areas that can be interacted with, causes the problem? See screenshot below

<img width="912" alt="Bildschirmfoto 2024-03-20 um 09 43 40" src="https://github.com/AdamSmasherDerby/Statsbook-Tool/assets/61935007/2e0da831-a0f1-491e-ac93-aa95926560fb">

This is Statsbook Tool 3.1.1. (MacOS) on MacOS 14.1.2

**Comment by AdamSmasherDerby** [comment]
This issue was addressed Sunday evening and a new version of the .DMG file uploaded at that time. Can you please download the tool again and see if that resolves the problem? Sent from my Galaxy
-------- Original message --------From: kayrie ***@***.***> Date: 3/20/24  1:52 AM  (GMT-08:00) To: AdamSmasherDerby/Statsbook-Tool ***@***.***> Cc: Subscribed ***@***.***> Subject: [AdamSmasherDerby/Statsbook-Tool] File selection and open routine
  issue in 3.1.1. (MacOS) (Issue #21) 
The file input box appears not to be working properly:

Choose a file opens the OS file open dialog, after selection of a file nothing else happens
drag and droping a file in this area is not functioning
clicking on the new button "Enter Google Sheets URL" is not functioning

may it be, that the new button in the UI is on top of other areas that can be interacted with, see screenshot below?
Bildschirmfoto.2024-03-20.um.09.43.40.png (view on web)
This is Statsbook Tool 3.1.1. (MacOS) on MacOS 14.1.2

**Comment by kayrie** [comment]
Hi Adam,
thanks - I missed the upload. Opening local file via dialog and drag&drop works now. The URL button now opens a dialogue asking for the URL. Unfortunately I cannot paste an URL in to the text box. I guess manually typing in an address is not the intended way.
Cheers, A. Lex

**Comment by AdamSmasherDerby** [comment]
Really?  That's fun.  I spend more time chasing down weird compilation issues on Macs... 

You're 100% correct that the intent is to be able to cut and paste.  

I'll have a look this evening.

**Comment by AdamSmasherDerby** [comment]
OK, cut and paste should now be working.  WHY do Macs have to be so %#*(@ idiosyncratic?
